### ISSUE TITLE
Missing dependency: aqueue

### ISSUE THREAD

**Issue by sbruchmann** [ConnorAtherton/typeout#3]
I installed `typeout` via `npm` and got the following error when I tried to require the module:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'aqueue'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/sbruchmann/code/foo/node_modules/typeout/src/typeout.js:14:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

This is easily fixed by placing `aqueue` in the `dependencies` directive instead of `devDependencies` in [package.json](https://github.com/ConnorAtherton/typeout/blob/98d9a3d8f163f7541d07fe61453775945710acd3/package.json).

**Comment by ConnorAtherton** [comment]
Hey @sbruchmann. Sorry about that, it's pretty late here and I just pushed a rewrite to this lib after work. I've published to npm again. Ping me if you have any more problems and I'll respond when I wake up :)
